[package]
name = "blur"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
nalgebra = "0.33.2"
photon-rs = { version = "0.3.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
